//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseDetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class agentdetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public agentdetail()
        {
            this.purchasebilldetails = new HashSet<purchasebilldetail>();
        }
    
        public int agent_id { get; set; }
        public string agent_name { get; set; }
        public Nullable<long> agent_contact { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<purchasebilldetail> purchasebilldetails { get; set; }
        public object AgentName { get; internal set; }
        public object AgentContact { get; internal set; }
    }
}
