//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PurchaseDetails.Models
{
    using System;
    using System.Collections.Generic;
    
    public   class purchasebilldetail
    {
        public int BillId { get; set; }
        public Nullable<System.DateTime> bill_date { get; set; }
        public Nullable<int> AgentId { get; set; }
        public Nullable<int> FarmerId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<decimal> Amount { get; set; }
    
        public virtual agentdetail agentdetail { get; set; }
        public virtual farmerdetail farmerdetail { get; set; }
        public virtual product product { get; set; }
        
  
        public object BillNo { get; internal set; }
        public object Farmer { get; internal set; }
        public object Agent { get; internal set; }
        public object AgentName {  get; internal set; }
        public object AgentContact { get; internal set; }
        public bool IsAgent { get; internal set; }
        public bool IsFarmer { get; internal set; }
        public DateTime BillDate { get; internal set; }
        // public DateTime BillDate { get; internal set; }

    }
}
